#!/usr/bin/env python3
"""Write include/config.h: the pairing with the daemon, Wi-Fi and options.

Usage: .venv/bin/python tools/make_config.py [options]

The pairing (host, port, token, certificate fingerprint) always comes fresh
from `agentctl pair`. Everything else is kept from the existing config.h
unless an option changes it, so after `agentctl pair --rotate` a plain run is
enough.

The file holds the panel token and the Wi-Fi password. It is written with
mode 600, is listed in .gitignore, and nothing secret is printed.
"""
import argparse
import getpass
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "include/config.h"

# Settings that survive a re-run, with their defaults.
KEPT = {
    "WIFI_SSID": '""',
    "WIFI_PASS": '""',
    "WIFI_NVS_NAMESPACE": None,          # not defined by default
    "PANEL_HOSTNAME": '"agents-deck-panel"',
}


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def read_defines(path: Path) -> dict[str, str]:
    """NAME -> raw value text for every `#define NAME value` on one line."""
    if not path.exists():
        return {}
    found = {}
    for m in re.finditer(r'^[ \t]*#define[ \t]+(\w+)[ \t]+("(?:[^"\\]|\\.)*"|\S+)[ \t]*$', path.read_text(), re.M):
        found[m.group(1)] = m.group(2)
    return found


def find_agentctl() -> str:
    path = shutil.which("agentctl") or str(Path.home() / ".local/bin/agentctl")
    if not Path(path).exists():
        sys.exit("agentctl not found. Install the agents-deck daemon first.")
    return path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--host", help="daemon host: mDNS name without .local, or an IPv4 address")
    wifi = ap.add_argument_group("Wi-Fi")
    wifi.add_argument("--ssid", help="network name; the password is asked for without echo")
    wifi.add_argument("--wifi-from", type=Path, metavar="HEADER",
                      help="copy the WIFI_SSID and WIFI_PASS defines of another firmware's header")
    wifi.add_argument("--wifi-nvs", metavar="NAMESPACE",
                      help='read "ssid" and "pass" from this NVS namespace first ("" turns it off)')
    opt = ap.add_argument_group("options")
    opt.add_argument("--hostname", help="the board's own network name")
    opt.add_argument("--break-pin", action="store_true",
                     help="write a wrong fingerprint, to test that the board refuses to pair")
    args = ap.parse_args()

    pair = json.loads(subprocess.run([find_agentctl(), "pair"], check=True, capture_output=True, text=True).stdout)
    url = urlparse(pair["url"])
    # urlparse().hostname lowercases the name; keep it as the daemon prints it.
    host = args.host or url.netloc.rsplit(":", 1)[0].removesuffix(".local")
    port = url.port or 7341
    token = pair["token"]
    if not re.fullmatch(r"[0-9a-f]{64}", token):
        sys.exit("unexpected token format from agentctl pair")
    m = re.fullmatch(r"sha256:((?:[0-9A-Fa-f]{2}:){31}[0-9A-Fa-f]{2})", pair["fingerprint"])
    if not m or not host:
        sys.exit("unexpected url or fingerprint format from agentctl pair")
    fp = bytearray.fromhex(m.group(1).replace(":", ""))
    if args.break_pin:
        fp[0] ^= 0xFF

    old = read_defines(OUT)
    kept = {name: old.get(name, default) for name, default in KEPT.items()}
    if args.wifi_from:
        other = read_defines(args.wifi_from.expanduser())
        for name in ("WIFI_SSID", "WIFI_PASS"):
            if name not in other:
                sys.exit(f"{args.wifi_from}: no {name} define")
            kept[name] = other[name]
    if args.ssid is not None:
        kept["WIFI_SSID"] = c_string(args.ssid)
        kept["WIFI_PASS"] = c_string(getpass.getpass(f"Wi-Fi password for {args.ssid}: "))
    if args.wifi_nvs is not None:
        kept["WIFI_NVS_NAMESPACE"] = c_string(args.wifi_nvs) if args.wifi_nvs else None
    if args.hostname:
        kept["PANEL_HOSTNAME"] = c_string(args.hostname)

    rows = [", ".join(f"0x{b:02X}" for b in fp[i:i + 8]) for i in range(0, 32, 8)]
    lines = [
        "// Generated by tools/make_config.py. Holds secrets: do not commit, do not share.",
        "#pragma once",
        "",
        "// Pairing with the daemon, from `agentctl pair`.",
        f"#define DECK_HOST  {c_string(host)}",
        f"#define DECK_PORT  {port}",
        f'#define DECK_TOKEN "{token}"',
        "#define DECK_FP    { " + ", \\\n                     ".join(rows) + " }",
        "",
        "// Wi-Fi.",
        f"#define WIFI_SSID  {kept['WIFI_SSID']}",
        f"#define WIFI_PASS  {kept['WIFI_PASS']}",
    ]
    if kept["WIFI_NVS_NAMESPACE"]:
        lines.append(f"#define WIFI_NVS_NAMESPACE {kept['WIFI_NVS_NAMESPACE']}")
    lines += [
        "",
        "// Options.",
        f"#define PANEL_HOSTNAME {kept['PANEL_HOSTNAME']}",
        "",
    ]
    OUT.parent.mkdir(exist_ok=True)
    fd = os.open(OUT, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write("\n".join(lines))
    os.chmod(OUT, 0o600)

    summary = [
        f"host {host}", f"port {port}", "fingerprint " + ":".join(f"{b:02X}" for b in fp[:2]) + ":…",
        "Wi-Fi " + ("set" if kept["WIFI_SSID"] != '""' else "not set"),
        "NVS " + (kept["WIFI_NVS_NAMESPACE"] or "off"),
        f"name {kept['PANEL_HOSTNAME']}",
    ]
    note = "  ** WRONG FINGERPRINT ON PURPOSE **" if args.break_pin else ""
    print(f"wrote {OUT.relative_to(ROOT)}: " + ", ".join(summary) + note)


if __name__ == "__main__":
    main()
