#!/usr/bin/env python3
"""Render Roboto Mono into fixed-cell 4-bpp bitmap fonts for lib/core/canvas.h.

Usage: .venv/bin/python tools/make_font.py [--preview out/font.png]

The source font ships with agents-deck (SIL OFL 1.1, see OFL-robotomono.txt).
Two fonts are written to lib/core/font_data.h: FONT_S and FONT_L.

font_data.h is checked in. Run this only to change sizes or the glyph set.
"""
import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
# This folder lives inside the agents-deck repository, or next to a clone of it.
_FONT = "backend/internal/web/static/fonts/RobotoMono.ttf"
TTF = next((p / _FONT for p in (ROOT.parent, ROOT.parent / "agents-deck") if (p / _FONT).exists()),
           ROOT.parent / _FONT)
OUT = ROOT / "lib/core/font_data.h"

# Roboto Mono advances 0.6 em, so these sizes give whole-pixel cells.
FONTS = [
    # name, cell width, weight
    ("S", 7, 500),
    ("L", 9, 500),
]

CODES = (
    list(range(0x20, 0x7F))
    + [0x0401] + list(range(0x0410, 0x0450)) + [0x0451]
    + [0x00B7, 0x00AB, 0x00BB, 0x2013, 0x2014, 0x2026, 0x2192, 0x2116]
)


def load(cell_w: int, weight: int) -> ImageFont.FreeTypeFont:
    font = ImageFont.truetype(str(TTF), cell_w / 0.6)
    font.set_variation_by_axes([weight])
    return font


def has_glyph(font: ImageFont.FreeTypeFont, code: int) -> bool:
    if code == 0x20:
        return True
    # A missing glyph renders as the font's .notdef box; compare with a code point that has none.
    return font.getmask(chr(code)).getbbox() != font.getmask("￿").getbbox() or \
        bytes(font.getmask(chr(code))) != bytes(font.getmask("￿"))


def render(name: str, cell_w: int, weight: int):
    font = load(cell_w, weight)
    ascent, descent = font.getmetrics()
    cell_h = ascent + descent
    codes = sorted(c for c in CODES if has_glyph(font, c))
    stride = (cell_w + 1) // 2
    bits = bytearray()
    for code in codes:
        img = Image.new("L", (cell_w, cell_h), 0)
        ImageDraw.Draw(img).text((0, ascent), chr(code), font=font, fill=255, anchor="ls")
        px = img.load()
        for y in range(cell_h):
            for bx in range(stride):
                hi = (px[bx * 2, y] + 8) // 17
                lo = (px[bx * 2 + 1, y] + 8) // 17 if bx * 2 + 1 < cell_w else 0
                bits.append(hi << 4 | lo)
    return {"name": name, "w": cell_w, "h": cell_h, "codes": codes, "bits": bytes(bits), "font": font,
            "ascent": ascent}


def c_array(values, per_line: int, fmt: str) -> str:
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("  " + ",".join(fmt % v for v in values[i:i + per_line]) + ",")
    return "\n".join(lines)


def write_header(fonts) -> None:
    out = [
        "// Generated by tools/make_font.py from RobotoMono.ttf (SIL OFL 1.1). Do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "// Fixed-cell font. Glyph i is cellH rows of (cellW + 1) / 2 bytes, two 4-bit",
        "// alpha values per byte, high nibble first. `codes` is sorted.",
        "struct Font {",
        "  uint8_t cellW, cellH;",
        "  uint16_t count;",
        "  const uint16_t* codes;",
        "  const uint8_t* bits;",
        "};",
        "",
    ]
    for f in fonts:
        n = f["name"]
        out += [
            f"static const uint16_t kFont{n}Codes[] = {{",
            c_array(f["codes"], 12, "0x%04X"),
            "};",
            f"static const uint8_t kFont{n}Bits[] = {{",
            c_array(f["bits"], 24, "0x%02X"),
            "};",
            f"static const Font FONT_{n} = {{{f['w']}, {f['h']}, {len(f['codes'])}, kFont{n}Codes, kFont{n}Bits}};",
            "",
        ]
    OUT.write_text("\n".join(out))


def preview(fonts, path: Path) -> None:
    sample = ["checkout-api running · 12m 41% $4.12", "Edit src/auth/session.ts → ok?",
              "Привет, Ёжик! Съешь ещё этих булок…", "0123456789 {}[]()<>/\\|_-+=*&^%$#@!~"]
    img = Image.new("RGB", (330, 160), (10, 10, 10))
    d = ImageDraw.Draw(img)
    y = 4
    for f in fonts:
        for line in sample:
            d.text((4, y + f["ascent"]), line, font=f["font"], fill=(232, 228, 220), anchor="ls")
            y += f["h"] + 1
        y += 4
    path.parent.mkdir(parents=True, exist_ok=True)
    img.resize((660, 320), Image.NEAREST).save(path)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", type=Path)
    args = ap.parse_args()
    fonts = [render(*f) for f in FONTS]
    write_header(fonts)
    for f in fonts:
        print(f"FONT_{f['name']}: cell {f['w']}x{f['h']}, {len(f['codes'])} glyphs, {len(f['bits'])} bytes")
    if args.preview:
        preview(fonts, args.preview)
        print("preview:", args.preview)


if __name__ == "__main__":
    main()
